const buttonOne = document.querySelector('.btn--one')
const buttonTwo = document.querySelector('.btn--two')

const questions = [
	'Czy lubisz seks oralny? Wolisz być stroną czynną czy bierną?',
	'Ile najwięcej razy w tygodniu uprawiałaś seks?',
	'Czy lubisz seks pod prysznicem?',
	'Czy zostałaś przyłapana na masturbacji?',
	'Jak często masz erotyczne myśli?',
	'Czy wolisz szybki i ostry seks, czy romantyczny i powolny?',
	'Czy kiedyś miałaś ochotę na seks w nieodpowiedniej sytuacji?',
	'Czego dotyczył twój ostatni sen erotyczny?',
	'Jak miała na imię osoba, z którą miałaś swój pierwszy raz?',
	'Czy czytałaś kiedyś erotyczne opowiadania?',
	'Czy myślałaś kiedyś o cuckold?',
	'Jak wyglądał twój pierwszy seks?',
	'Czy kiedykolwiek nie zdążyłaś do toalety?',
	'Czy kiedykolwiek nie zmieniłaś bielizny przez kilka dni? - Jeśli tak to przez ile dni',
	'Jaki był Twój najlepszy sen erotyczny?',
	'Którą część ciała chłopaka / dziewczyny lubisz najbardziej i dlaczego?',
	'Na jakiej części ciała kobiety najbardziej lubisz kończyć?',
	'Ile najwięcej orgazmów miałeś jednego dnia?',
	'W jaki sposób najszybciej doprowadzić cię do orgazmu?',
	'Ile czasu powinien trwać według ciebie idealny seks?',
	'Czego nie lubisz, jeśli chodzi o sprawy seksualne?',
	'Wolisz uprawiać seks rano, czy wieczorem?',
	'Wolałbyś przespać się z najbrzydszą kobietą świata, czy już nigdy nie móc uprawiać seksu?',
	'Czy miałeś przedwczesny wytrysk?',
	'Czy byłeś kiedyś zdominowany przez dziewczynę?',
	'Czy wyobrażasz sobie romansować z którąś nauczycielką?',
	'Seks ostry i szybki, czy romantyczny i powolny?',
	'Jaki kolor bielizny jest według Ciebie najbardziej seksowny?',
	'Czy kiedykolwiek miałeś fantazje seksualne o swojej nauczycielce?',
	'Czy uważasz, że jesteś dobry w łóżku?',
	'Czy kiedykolwiek posikałeś się przez sen?',
	'Czy miałeś kiedyś sen erotyczny o kimś z rodziny?',
	'Czy kiedykolwiek miałeś erekcję na lekcji?',
	'Kogo chciałbyś najbardziej zobaczyć nago?',
	'Czy kręciłeś kiedyś z dwoma dziewczynami naraz?',
	'Czy wolałbyś zjeść pająka czy uprawiać seks z osobą, która ma zespół downa?',
	'Wolałbyś mieć penisy zamiast palców, czy palec zamiast penisa?',
	'Wolałbyś zjeść kostkę masła, czy wypić szklankę oleju?',
	'Jaki był Twój najobrzydliwszy sen kiedykolwiek?',
	'Wolałbyś wymiotować ślimakami, czy pocić się moczem?',
	'Co robisz jak jesteś sam w domu?',
	'Jak często chciałabyś uprawiać seks?',
	'Na co nigdy nie zgodziłabyś się podczas zbliżenia seksualnego?',
	'Czy próbowałaś kiedyś wcielać się w role podczas seksu? Jakie?',
	'Wolisz podczas seksu być na górze, czy na dole?',
	'Czy uprawiałeś kiedyś seks w trójkącie?',
	'Czy przespałbyś się z którymś ze swoim przyjaciół?',
	'Czy mogłabyś pracować jako camgirl?',
	'Co sądzisz o seksie, gdy w domu są rodzice?',
	'Czego nigdy byś nie zrobiła w łóżku?',
	'Czy podobała Ci się kiedyś zajęta kobieta?',
	'Jaka część ciała kobiety najbardziej Cię kręci?',
	'Czy ktoś kiedyś przyłapał Cię na seksie/masturbacji?',
	'Czy uprawiałeś seks z osobą z innego kraju?',
	'Jaki gadżet erotyczny jest Twoim zdaniem najlepszy i dlaczego?',
	'Czy zdarzyło Ci się zapomnieć imienia osoby, z którą się całowałeś?',
	'Czy kiedykolwiek tańczyłeś dla kogoś taniec erotyczny?',
	'Jaka jest twoja największa fantazja seksualna?',
	'Czy kiedykolwiek żałowałeś seksu z jakąś osobą?',
	'Czy uprawiałeś kiedyś seks w miejscu publicznym? Jeśli tak, gdzie?',
	'Jaka jest twoja ulubiona pozycja seksualna?',
	'Z iloma osobami uprawiałeś seks?',
	'Jaka jest długość twojego penisa?',
	'Ile razy w tygodniu/miesiącu uprawiasz seks?',
	'Czy zdarzyło Ci się dojść za szybko?',
	'Jaki rozmiar piersi najbardziej lubisz?',
	'Czy masz jakieś fetysze seksualne jak tak to jakie?',
	'Co najbardziej cię podnieca w płci przeciwnej?',
	'Czy fantazjowałaś kiedyś o seksie z obcą osobą?',
	'Czy miałaś kiedyś romans z dziewczyną?',
	'Jeśli mogłabyś wybrać jedną osobę na świecie z którą uprawiałabyś seks, kto by to był?',
	'W jakiej pozycji najszybciej osiągasz orgazm?',
	'Czy masz zabawki erotyczne? Jeśli tak, jakie?',
	'Jaka jest twoja największa fantazja seksualna, której nie udało ci się jeszcze spełnić?',
	'Wolisz być dominująca czy uległa podczas seksu?',
	'Czy kręcą cię tatuaże i piercing u płci przeciwnej?',
	'Jakiej pozycji seksualnej nie lubisz i dlaczego?',
	'Czy żałowałaś kiedyś seksu z jakąś osobą?',
	'Jaka jest Twoja ulubiona strona z pornografią?',
	'Czy kiedyś dołączyłeś do seksu gadżety erotyczne?',
	'Czy myślałeś kiedyś w sposób seksualny o kimś, o kim wiesz, że nie powinieneś? Jeśli tak to kto to był',
	'Czy próbowałeś seksu BDSM? Jeśli nie, to chciałbyś?',
	'Czy zadowala cię twój rozmiar przyrodzenia?',
	'Wolisz kobiety dominujące czy uległe w łóżku?',
	'Czy uprawiałeś kiedyś seks w samochodzie?',
	'Czy uprawiałeś kiedykolwiek seks analny?',
	'Z kim ze znanych osób najbardziej chciałbyś pójść do łóżka?',
	'Czy zdarzyło ci się kiedyś uprawiać cyber seks?',
	'Czy kiedykolwiek wysyłałaś nagie zdjęcia?',
	'Czy rozmiar penisa partnera ma dla ciebie znaczenie?',
	'Czy uprawiałaś kiedyś seks bez zobowiązań?',
	'Wolisz facetów / dziewczyny szczupłych, umięśnionych czy pulchnych?',
	'Ile najwięcej miałaś orgazmów podczas jednego seksu?',
	'Czy kiedykolwiek miałaś orgazm w miejscu publicznym?',
	'Czy pisałaś z kimś kiedyś erotyczne wiadomości?',
	'Czy kiedykolwiek udawałaś orgazm?',
	'Jaką bieliznę nosisz najczęściej?',
	'Ile razy w tygodniu się masturbujesz?',
	'Jaka jest twoja ulubiona kategoria porno?',
	'Czy kiedykolwiek uprawiałeś seks z osobą, której nie znasz?',
	'Czy byłeś kiedyś w układzie friends with benefits?',
	'Czy uważasz, że One Night Stand pasuje do Ciebie?',
	'Gdybyś musiała odbyć stosunek z jakąś kobietą, kim by była wybrana dziewczyna?',
	'Czy kiedykolwiek nagrywałeś siebie podczas seksu?',
	'Jaki jest najgorszy tekst na podryw, który usłyszałaś?',
	'W jaki sposób wyrywasz najczęściej dziewczyny?',
	'Czy byłabyś w stanie poderwać chłopaka / dziewczyne starszego / starszą o 10 lat?',
	'Czy kiedykolwiek próbowałaś seksu z zakrytymi oczami?',
	'Czy chciałabyś uprawiać seks w trojkącie lub w orgii?',
	'Czy kiedykolwiek masturbowałaś się przy użyciu niecodziennego przedmiotu?',
	'Jak często oglądasz filmy pornograficzne?',
	'Jaki ubiór u mężczyzny / dziewczyn cię najbardziej podnieca?',
]

const challanges = [
	'Wykonaj 100 przysiadów',
	'Pokaż najbardziej żenujące zdjęcie w telefonie',
	'Powiedz coś brudnego osobie po twojej lewej stronie',
	'Zjedz banana bez użycia rąk',
	'Trelujprzez minutę',
	'Zjedz surową cebulę',
	'Trzymaj trzy kostki lodu w ustach, aż się rozpuszczą',
	'Wykrzycz pierwsze słowo, które przyjdzie ci do głowy',
	'Pochwal się swoją twarzą z orgazmem',
	'Pokaż pięć ostatnich osób, do których wysyłałeś SMS-y, i treść wiadomości',
	'Spróbuj włożyć całą pięść do ust',
	'Usuń dwie części garderoby',
	'Zjedz łyżkę musztardy',
	'Wlej od 3 do 10 różnych dostępnych płynów do kubka i wypij',
	'Spróbuj polizać łokieć',
	'Spróbuj zrobić sobie loda',
	'Udawaj, że jesteś osobą po twojej prawej stronie przez 5 minut',
	'Bądź czyimś zwierzakiem przez następne 5 minut',
	'Spróbuj wypić szklankę wody stojąc na rękach',
	'Włóż do ust tyle przekąsek na raz, ile możesz',
	'Spróbuj jak najszybciej rozśmieszyć grupę',
	'Opowiedz wszystkim wstydliwą historię o sobie',
	'Niech ktoś ogoli część twojego ciała',
	'Taniec brzucha, jakby od tego zależało twoje życie',
	'Przeklinaj jak marynarz przez 20 sekund z rzędu',
	'Wyć jak wilk',
	'Tańcz bez muzyki przez minutę',
	'Daj się połaskotać komuś innemu i postaraj się nie śmiać',
	'Naśladuj osobę po swojej prawej stronie',
	'Spróbuj zrobić magiczną sztuczkę',
	'Zrób robaka',
	'Rozbij dwa jajka na głowie',
	'Płukać gardło czymś, co nie powinno być płukane, ale nie zrobi ci krzywdy',
	'Daj się spoliczkować przez wybraną przez siebie osobę',
	'Skomponuj wiersz na miejscu na podstawie coś, co wymyśli grupa',
	'Wybierz kogoś z grupy, aby dać ci klapsa',
	'Przeciągnij tyłek po dywanie jak pies z jednego końca pokoju na drugi',
	'Otwórz paczkę przekąsek lub cukierków używając tylko ust, bez rąk i stóp',
	'Idź do łazienki, zdejmij bieliznę i załóż ją na głowę. Noś go na głowie do końca gry',
	'Zjedz jedną łyżeczkę najostrzejszej rzeczy, jaką masz w kuchni',
	'Udawaj, że jesteś jedzeniem. Nie udawaj, że jesz, udawaj, że jesteś jedzeniem. Udawaj, aż ktoś z grupy odgadnie, kim jesteś',
	'Wrzuć coś do toalety, a następnie sięgnij po to',
	'Włóż kostki lodu do spodni',
	'Musisz polizać podłogę',
	'Zamień się ubraniami z osobą przeciwnej płci w grupie na trzy rundy',
	'Niech grupa ustawi cię w zawstydzającej pozycji i zrób zdjęcie',
	'Pozwól grupie przeglądać Twój telefon przez minutę',
	'Wypij małą filiżankę mikstury, którą robi grupa',
	'Wykonuj pompki, aż nie będziesz w stanie zrobić więcej, odczekaj 5 sekund, a następnie zrób jeszcze jedną',
	'Udawaj płeć przeciwną',
	'Mów przez 10 minut „wszystko gra, nie nic nie gra, a może gra',
	'Poczuj zapach pod pachą innego gracza',
	'Zjedz kawałek skórki od banana',
	'Mów ogórki na końcu każdego wypowiedzianego zdania, aż znowu nadejdzie twoja kolej',
	'Zadzwoń do przyjaciela, udawaj, że są jego urodziny i zaśpiewaj mu Happy Birthday',
	'Załóż opaskę na oczy i dotykaj twarzy innych graczy, aż będziesz mógł dowiedzieć się, kto jest kim',
	'Pozwól innemu graczowi stworzyć czapkę z papieru toaletowego — i musisz ją nosić do końca gry',
	'Rób deskę przez pełną minutę',
	'Szczekać jak pies',
	'Powtarzaj wszystko, co mówi osoba po twojej prawej stronie, aż do następnej tury',
	'Połóż się na podłodze i zachowuj jak skwierczący kawałek bekonu',
	'Poliż kostkę mydła',
	'Zjedz łyżkę majonezu',
	'Przeczytaj na głos pięć ostatnich wyszukiwań w telefonie',
	'',
]

const generatorQuest = () => {
	const textOne = document.querySelector('.question')
	const numbers = Math.floor(Math.random() * questions.length)

	textOne.textContent = questions[numbers]
}

const challangeGenerator = () => {
	const textTwo = document.querySelector('.challenge')
	const numbers = Math.floor(Math.random() * challanges.length)

	textTwo.textContent = challanges[numbers]
}

buttonOne.addEventListener('click', generatorQuest)
buttonTwo.addEventListener('click', challangeGenerator)
